force-app/main/StockSolution/objects/Opportunity/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Installed_Date__c.field-meta.xml
<CustomField>
    <fullName>Installed_Date__c</fullName>
    <label>Installed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
            <value>
                <fullName>Defected</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/StockSolution/classes/TH_OpportunityStock.cls
/**
 * Created by JurgitaG on 1/17/2023.
 */

public class TH_OpportunityStock
{
	public static final String STAGE_CLOSED_WON = 'Closed Won';
	public static final String STAGE_CLOSED_LOST = 'Closed Lost';
	public static final String STOCK_STATUS_INSTALLED = 'Installed';
	public static final String STOCK_STATUS_INSTOCK = 'In Stock';
	public static final String STOCK_STATUS_RESERVED = 'Reserved';

	List<Stock__c> stockToUpdate = new List<Stock__c>();
	Set<Id> accountIds = new Set<Id>();

	public void checkOpportunitiesWithStock(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOppMap)
	{
		for (Opportunity newOpp : newOpportunities)
		{
			if (!oldOppMap.containsKey(newOpp.Id))
			{
				if (newOpp.Stock__c != null)
				{
					addStockForUpdate(newOpp, STOCK_STATUS_RESERVED);
					accountIds.add(newOpp.AccountId);
				}
				continue;
			}
			Opportunity oldOpp = oldOppMap.get(newOpp.Id);

			if (newOpp.StageName == STAGE_CLOSED_WON && newOpp.StageName != oldOpp.StageName)
			{
				handleOpportunityWon(newOpp);
				accountIds.add(newOpp.AccountId);
				continue;
			}
			if (newOpp.StageName == STAGE_CLOSED_LOST && newOpp.StageName != oldOpp.StageName)
			{
				addStockForUpdate(newOpp, STOCK_STATUS_INSTOCK);
				accountIds.add(newOpp.AccountId);
				continue;
			}
			if (newOpp.Stock__c != oldOpp.Stock__c)
			{
				if (newOpp.Stock__c != null)
				{
					addStockForUpdate(newOpp, STOCK_STATUS_RESERVED);
				}
				else {
					addStockForUpdate(oldOpp, STOCK_STATUS_INSTOCK);
				}
				accountIds.add(newOpp.AccountId);
			}

		}
	}

	public void handleOpportunityDelete(List<Opportunity> opportunities)
	{
		for (Opportunity newOpp : opportunities)
		{
			if (newOpp.Stock__c != null)
			{
				addStockForUpdate(newOpp, STOCK_STATUS_INSTOCK);
			}
			accountIds.add(newOpp.AccountId);
		}
	}
	private void addStockForUpdate(Opportunity opp, String status)
	{
		stockToUpdate.add(new Stock__c(
				Id = opp.Stock__c,
				Status__c = status
		));
	}
	private void handleOpportunityWon(Opportunity opp)
	{
		if (opp.Stock__c == null || opp.AccountId == null)
		{
			return;
		}
		stockToUpdate.add(new Stock__c(
				Id = opp.Stock__c,
				Status__c = STOCK_STATUS_INSTALLED,
				Installed_Date__c = Date.today(),
				Account__c = opp.AccountId
		));
	}
	public void updateStock(){
		update stockToUpdate;
		BLL_AccountStockUpdate.updateAccounts(accountIds);
	}
}