force-app/main/StockSolution/objects/Account/fields/Last_Stock_Installed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Stock_Installed_Date__c</fullName>
    <label>Last Stock Installed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/StockSolution/objects/Account/fields/Reserved_Price__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Price__c</fullName>
    <label>Reserved Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/StockSolution/objects/Account/fields/Stock_Reserved__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reserved__c</fullName>
    <label>Stock Reserved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/StockSolution/objects/Account/fields/Total_Owned_Stock__c.field-meta.xml
<CustomField>
    <fullName>Total_Owned_Stock__c</fullName>
    <label>Total Owned Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/StockSolution/objects/Opportunity/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Installed_Date__c.field-meta.xml
<CustomField>
    <fullName>Installed_Date__c</fullName>
    <label>Installed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/StockSolution/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
            <value>
                <fullName>Defected</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/StockSolution/classes/BLL_AccountStockUpdate.cls
/**
 * Created by JurgitaG on 1/17/2023.
 */

public with sharing class BLL_AccountStockUpdate
{
	@Future
	public static void updateAccounts(Set<Id> accountIds) {
		List<AggregateResult> reservedStock = [
				SELECT SUM(Stock__r.Price__c) reservedPrice, COUNT(Stock__c) reservedCount, AccountId FROM Opportunity
				WHERE Stock__r.Status__c =:TH_OpportunityStock.STOCK_STATUS_RESERVED AND AccountId IN:accountIds GROUP BY AccountId
		];
		List<AggregateResult> installedStock = [
				SELECT MAX(Installed_Date__c) lastInstalled, COUNT(Id) countOfInstalled, Account__c FROM Stock__c
				WHERE Account__c IN:accountIds GROUP BY Account__c
		];
		Map<Id, Account> accountToUpdate = new Map<Id, Account>();
		for (AggregateResult result : reservedStock){
			String accountId = String.valueOf(result.get('AccountId'));
			if (accountToUpdate.containsKey(accountId))
			{
				Account updateAccount = accountToUpdate.get(accountId);
				updateAccount.Reserved_Price__c = (Decimal) result.get('reservedPrice');
				updateAccount.Stock_Reserved__c = (Decimal) result.get('reservedCount');
			}
			else {
				accountToUpdate.put(accountId, new Account(
						Id =accountId,
						Reserved_Price__c = (Decimal) result.get('reservedPrice'),
						Stock_Reserved__c = (Decimal) result.get('reservedCount')
				));
			}
		}
		for (AggregateResult result : installedStock){
			String accountId = String.valueOf(result.get('AccountId'));
			if (accountToUpdate.containsKey(accountId))
			{
				Account updateAccount = accountToUpdate.get(accountId);
				updateAccount.Last_Stock_Installed_Date__c = (Date) result.get('lastInstalled');
				updateAccount.Total_Owned_Stock__c = (Decimal) result.get('countOfInstalled');
			}
			else {
				accountToUpdate.put(accountId, new Account(
						Id =accountId,
						Last_Stock_Installed_Date__c = (Date) result.get('lastInstalled'),
						Total_Owned_Stock__c = (Decimal) result.get('countOfInstalled')
				));
			}
		}
		update accountToUpdate.values();
	}
}